spring.application.name=adonai
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/topburguer
spring.datasource.username=topburguer
spring.datasource.password=topburguer-api

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect